name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'v0.147.3'

      - name: Construir o site
        run: hugo --minify

      - name: Publicar na branch gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages

